#!/bin/bash

set -e

version="$1"
template="/usr/lib/olinuxino/kernel.its"

# Check if FIT template exists
if [[ ! -e ${template} ]]; then
    echo >&2 "W: uboot-fit: FIT image template file is missing"
    exit 2
fi

echo >&1 "Generating FIT source"
sed "s/\${VERSION}/${version}/g" ${template} > /boot/kernel.its

echo >&1 "Generating FIT image"
mkimage -f /boot/kernel.its /boot/kernel.itb > /dev/null
