#!/bin/bash

set -e

EXCLUDE=("/dev/*" "/proc/*" "/sys/*" "/media/*" "/mnt/*" "/run/*" "/tmp/*")
ROOT_DIR=$(dirname "$0")

source ${ROOT_DIR}/library.sh

function required_blocks
{
    _exclude=""
    for e in "${EXCLUDE[@]}"; do
        _exclude=${_exclude}" --exclude=${e}"
    done

    du -s --block-size=512 ${_exclude} / | awk '{print $1}'
}

echo -e "\nDetecting board..."
for comp in $(cat "/proc/device-tree/compatible" | tr '\0' '\n'); do
	if [[ "$comp" == "allwinner,sun"* ]]; then
		_soc=$(cut -d',' -f2 <<< $comp)
		break
    fi
done

if [[ -z ${_soc} ]]; then
    echo "Failed to detect the board type!" >&2
    exit 1
fi

case ${_soc} in
    "sun5i-a13")
        _board="a13-olinuxino"
        ;;
    "sun7i-a20")
        _board="a20-olinuxino"
        ;;
    "sun50i-a64")
        _board="a64-olinuxino"
        ;;
    *)
        echo "Unsupported board family: ${_soc}!" >&2
        exit 1
        ;;
esac


echo -e "\nDetecting the root device..."
_root_partition=$(get_root_partition)
if [[ -z ${_root_partition} ]]; then
    echo "Failed to detect root partition!" >&2
    exit 1
fi

_root_device=$(get_root_device)
if [[ -z ${_root_device} ]]; then
    echo "Failed to detect root device!" >&2
    exit 1
fi
echo -e "Root partition:\t\t${_root_partition}"
echo -e "Root device:\t\t${_root_device}"

echo -e "\nDetecting eMMC device..."
_emmc_device=$(get_emmc_device)
_emmc_partition=$(sed "s/${_root_device#/dev/}/${_emmc_device#/dev/}/g" <<< ${_root_partition})

if [[ -z ${_emmc_device} ]]; then
    echo "Failed to detect eMMC device!" >&2
    exit 1
fi
echo -e "eMMC partition:\t\t${_emmc_partition}"
echo -e "eMMC device:\t\t${_emmc_device}"

echo -e "\nChecking disk size..."
_required=$(required_blocks)
_available=$(get_device_block_count ${_emmc_device})

echo -e "Required blocks:\t${_required}"
echo -e "Available blocks:\t${_available}"

if [[ ${_available} -lt ${_required} ]]; then
    echo "Not enough blocks to transfer the file-system!" >&2
    exit 1
fi

echo -e "\nUnmount target device..."
umount ${_emmc_partition} || true
sync

echo -e "\nCopying MBR record..."
dd if=/dev/zero of=${_emmc_device} bs=1M count=1 conv=sync,fsync 2>/dev/null
sync
sfdisk -q -d ${_root_device} | sfdisk -q --wipe=always ${_emmc_device}

echo -e "\nResizing partition..."
resize_partition ${_emmc_partition}
e2fsck -f ${_emmc_partition}
resize2fs ${_emmc_partition}

echo -e "\nFormating disk..."
_type=$(get_partition_type ${_root_partition})
mkfs.${_type} -F ${_emmc_partition} > /dev/null 2>&1

echo -e "\nCopying disk..."
_mount=$(mktemp -d)
mount ${_emmc_partition} ${_mount}

_exclude=""
    for e in "${EXCLUDE[@]}"; do
        _exclude=${_exclude}" --exclude=${e}"
    done

rsync -a --info=progress2 --delete ${_exclude} / ${_mount}

echo -e "\nConfiguring..."
_root_uuid=$(get_partition_uuid ${_root_partition})
_emmc_uuid=$(get_partition_uuid ${_emmc_partition})
sed -i "s/${_root_uuid}/${_emmc_uuid}/g" ${_mount}/etc/fstab

echo -e "\nCleanup..."
umount ${_emmc_partition} || true
sync
rm -rf ${_mount}

echo -e "\nWriting bootloader..."
# TODO: Use u-boot scripts
dd if=/lib/u-boot-olinuxino/${_board}/u-boot-sunxi-with-spl.bin of=${_emmc_device} bs=1k seek=8
