#!/bin/bash

# Get the root partition
for arg in $(cat /proc/cmdline); do
    case $arg in
    "root="*)
            ROOT=${arg#root=}
            break
        ;;

    *)
        ;;

    esac
done

[[ -z $ROOT ]] && \
    echo "Could not detect root device!" && \
    exit 1

# Get device
ROOT_PART=$(blkid | grep "${ROOT#PARTUUID=}" | cut -d':' -f1)
echo "Detected root partition: ${ROOT_PART}"

# The following doesn't work on debian sid.
DEVICE=$(lsblk -n -o PKNAME "${ROOT_PART}" | head -n1)
# Try regex expression
if [[ -z ${DEVICE} ]]; then
    [[ ${ROOT_PART} =~ "/dev/mmcblk"[0-9]+ ]] || \
    [[ ${ROOT_PART} =~ "/dev/sd"[a-z] ]] && \
    DEVICE=${BASH_REMATCH[0]}
else
    DEVICE="/dev/${DEVICE}"
fi
[[ -z ${DEVICE} ]] && echo >&2 "Failed to determine the parent of ${ROOT_PART}." && exit 1
PART_COUNT=$(fdisk -l "${DEVICE}" | grep -c "^${DEVICE}p")

# Get boundaries
while read -r line; do
    grep -q "^${ROOT_PART}" <<< "${line}" || continue

    PART_START="$(awk -F' ' '{print $2}' <<< "${line}")"
done <<< "$(fdisk -l "${DEVICE}")"


# Commands are different for single and multi-partition devices
if [[ ${PART_COUNT} -eq 1 ]]; then
    fdisk "${DEVICE}" << __EOF__
d
n
p
1
${PART_START}

w
__EOF__
else
    fdisk "${DEVICE}" << __EOF__
d
${ROOT_PART#${DEVICE}p}
n
p
${ROOT_PART#${DEVICE}p}
${PART_START}

w
__EOF__
fi

# Expand
resize2fs "${ROOT_PART}"

# Disable service
systemctl disable olinuxino-expand.service